title: algorithm and data structure
description: >-
  This programme provides students with the chance to obtain key knowledge and
  skills required for their future career in a wide range of technology-related
  areas – from systems analysis and programming to internet application
  development and user experienc
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
